package Panopto::Interface::UsageReporting;

use Panopto;

# Generated by SOAP::Lite (v0.714) for Perl -- soaplite.com
# Copyright (C) 2000-2006 Paul Kulchenko, Byrne Reese
# -- generated at [Mon Aug 12 17:18:56 2013]
# -- generated from http://demo.hosted.panopto.com/Panopto/PublicAPI/4.2/UsageReporting.svc?wsdl
my %methods = (
GetSessionUserDetailedUsage => {
    endpoint => '/Panopto/PublicAPI/4.2/UsageReporting.svc',
    soapaction => 'http://tempuri.org/IUsageReporting/GetSessionUserDetailedUsage',
    namespace => 'http://tempuri.org/',
    parameters => [
    ], # end parameters
  }, # end GetSessionUserDetailedUsage
GetFolderSummaryUsage => {
    endpoint => '/Panopto/PublicAPI/4.2/UsageReporting.svc',
    soapaction => 'http://tempuri.org/IUsageReporting/GetFolderSummaryUsage',
    namespace => 'http://tempuri.org/',
    parameters => [
    ], # end parameters
  }, # end GetFolderSummaryUsage
GetSessionSummaryUsage => {
    endpoint => '/Panopto/PublicAPI/4.2/UsageReporting.svc',
    soapaction => 'http://tempuri.org/IUsageReporting/GetSessionSummaryUsage',
    namespace => 'http://tempuri.org/',
    parameters => [
    ], # end parameters
  }, # end GetSessionSummaryUsage
GetUserDetailedUsage => {
    endpoint => '/Panopto/PublicAPI/4.2/UsageReporting.svc',
    soapaction => 'http://tempuri.org/IUsageReporting/GetUserDetailedUsage',
    namespace => 'http://tempuri.org/',
    parameters => [
    ], # end parameters
  }, # end GetUserDetailedUsage
GetSessionDetailedUsage => {
    endpoint => '/Panopto/PublicAPI/4.2/UsageReporting.svc',
    soapaction => 'http://tempuri.org/IUsageReporting/GetSessionDetailedUsage',
    namespace => 'http://tempuri.org/',
    parameters => [
    ], # end parameters
  }, # end GetSessionDetailedUsage
GetSystemSummaryUsage => {
    endpoint => '/Panopto/PublicAPI/4.2/UsageReporting.svc',
    soapaction => 'http://tempuri.org/IUsageReporting/GetSystemSummaryUsage',
    namespace => 'http://tempuri.org/',
    parameters => [
    ], # end parameters
  }, # end GetSystemSummaryUsage
); # end my %methods

use SOAP::Lite;
use Exporter;
use Carp ();

use vars qw(@ISA $AUTOLOAD @EXPORT_OK %EXPORT_TAGS);
@ISA = qw(Exporter SOAP::Lite);
@EXPORT_OK = (keys %methods);
%EXPORT_TAGS = ('all' => [@EXPORT_OK]);

sub _call {
    my ($self, $method) = (shift, shift);
    my $name = UNIVERSAL::isa($method => 'SOAP::Data') ? $method->name : $method;
    my %method = %{$methods{$name}};

    $self->proxy('http://' . Panopto->ServerName . $method{endpoint} || Carp::croak "No server address (proxy) specified")
        unless $self->proxy;
    my @templates = @{$method{parameters}};
    my @parameters = ();
    foreach my $param (@_) {
        if (@templates) {
            my $template = shift @templates;
            my ($prefix,$typename) = SOAP::Utils::splitqname($template->type);
            my $method = 'as_'.$typename;
            # TODO - if can('as_'.$typename) {...}
            my $result = $self->serializer->$method($param, $template->name, $template->type, $template->attr);
            push(@parameters, $template->value($result->[2]));
        }
        else {
            push(@parameters, $param);
        }
    }
    $self->endpoint('http://' . Panopto->ServerName . $method{endpoint})
       ->ns($method{namespace})
       ->on_action(sub{qq!"$method{soapaction}"!});
    $self->serializer->register_ns("http://tempuri.org/","tns");
    my $som = $self->SUPER::call($method => @parameters);
    if ($self->want_som) {
        return $som;
    }
    UNIVERSAL::isa($som => 'SOAP::SOM') ? wantarray ? $som->paramsall : $som->result : $som;
}

sub BEGIN {
    no strict 'refs';
    for my $method (qw(want_som)) {
        my $field = '_' . $method;
        *$method = sub {
            my $self = shift->new;
            @_ ? ($self->{$field} = shift, return $self) : return $self->{$field};
        }
    }
}
no strict 'refs';
for my $method (@EXPORT_OK) {
    my %method = %{$methods{$method}};
    *$method = sub {
        my $self = UNIVERSAL::isa($_[0] => __PACKAGE__)
            ? ref $_[0]
                ? shift # OBJECT
                # CLASS, either get self or create new and assign to self
                : (shift->self || __PACKAGE__->self(__PACKAGE__->new))
            # function call, either get self or create new and assign to self
            : (__PACKAGE__->self || __PACKAGE__->self(__PACKAGE__->new));
        $self->_call($method, @_);
    }
}

sub AUTOLOAD {
    my $method = substr($AUTOLOAD, rindex($AUTOLOAD, '::') + 2);
    return if $method eq 'DESTROY' || $method eq 'want_som';
    die "Unrecognized method '$method'. List of available method(s): @EXPORT_OK\n";
}

1;
