package Panopto::Interface::UserManagement;

use Panopto;

# Generated by SOAP::Lite (v0.714) for Perl -- soaplite.com
# Copyright (C) 2000-2006 Paul Kulchenko, Byrne Reese
# -- generated at [Mon Aug 12 17:12:46 2013]
# -- generated from https://demo.hosted.panopto.com/Panopto/PublicAPI/4.2/UserManagement.svc?wsdl


my %methods = (
GetUsers => {
    endpoint => '/Panopto/PublicAPI/4.2/UserManagement.svc',
    soapaction => 'http://tempuri.org/IUserManagement/GetUsers',
    namespace => 'http://tempuri.org/',
    parameters => [
    ], # end parameters
  }, # end GetUsers
UpdateUserBio => {
    endpoint => '/Panopto/PublicAPI/4.2/UserManagement.svc',
    soapaction => 'http://tempuri.org/IUserManagement/UpdateUserBio',
    namespace => 'http://tempuri.org/',
    parameters => [
    ], # end parameters
  }, # end UpdateUserBio
CreateExternalGroup => {
    endpoint => '/Panopto/PublicAPI/4.2/UserManagement.svc',
    soapaction => 'http://tempuri.org/IUserManagement/CreateExternalGroup',
    namespace => 'http://tempuri.org/',
    parameters => [
    ], # end parameters
  }, # end CreateExternalGroup
DeleteUsers => {
    endpoint => '/Panopto/PublicAPI/4.2/UserManagement.svc',
    soapaction => 'http://tempuri.org/IUserManagement/DeleteUsers',
    namespace => 'http://tempuri.org/',
    parameters => [
    ], # end parameters
  }, # end DeleteUsers
CreateUser => {
    endpoint => '/Panopto/PublicAPI/4.2/UserManagement.svc',
    soapaction => 'http://tempuri.org/IUserManagement/CreateUser',
    namespace => 'http://tempuri.org/',
    parameters => [
    ], # end parameters
  }, # end CreateUser
SetGroupIsPublic => {
    endpoint => '/Panopto/PublicAPI/4.2/UserManagement.svc',
    soapaction => 'http://tempuri.org/IUserManagement/SetGroupIsPublic',
    namespace => 'http://tempuri.org/',
    parameters => [
    ], # end parameters
  }, # end SetGroupIsPublic
UnlockAccount => {
    endpoint => '/Panopto/PublicAPI/4.2/UserManagement.svc',
    soapaction => 'http://tempuri.org/IUserManagement/UnlockAccount',
    namespace => 'http://tempuri.org/',
    parameters => [
    ], # end parameters
  }, # end UnlockAccount
SetSystemRole => {
    endpoint => '/Panopto/PublicAPI/4.2/UserManagement.svc',
    soapaction => 'http://tempuri.org/IUserManagement/SetSystemRole',
    namespace => 'http://tempuri.org/',
    parameters => [
    ], # end parameters
  }, # end SetSystemRole
ResetPassword => {
    endpoint => '/Panopto/PublicAPI/4.2/UserManagement.svc',
    soapaction => 'http://tempuri.org/IUserManagement/ResetPassword',
    namespace => 'http://tempuri.org/',
    parameters => [
    ], # end parameters
  }, # end ResetPassword
GetGroupIsPublic => {
    endpoint => '/Panopto/PublicAPI/4.2/UserManagement.svc',
    soapaction => 'http://tempuri.org/IUserManagement/GetGroupIsPublic',
    namespace => 'http://tempuri.org/',
    parameters => [
    ], # end parameters
  }, # end GetGroupIsPublic
UpdatePassword => {
    endpoint => '/Panopto/PublicAPI/4.2/UserManagement.svc',
    soapaction => 'http://tempuri.org/IUserManagement/UpdatePassword',
    namespace => 'http://tempuri.org/',
    parameters => [
    ], # end parameters
  }, # end UpdatePassword
SyncExternalUser => {
    endpoint => '/Panopto/PublicAPI/4.2/UserManagement.svc',
    soapaction => 'http://tempuri.org/IUserManagement/SyncExternalUser',
    namespace => 'http://tempuri.org/',
    parameters => [
    ], # end parameters
  }, # end SyncExternalUser
DeleteGroup => {
    endpoint => '/Panopto/PublicAPI/4.2/UserManagement.svc',
    soapaction => 'http://tempuri.org/IUserManagement/DeleteGroup',
    namespace => 'http://tempuri.org/',
    parameters => [
    ], # end parameters
  }, # end DeleteGroup
UpdateContactInfo => {
    endpoint => '/Panopto/PublicAPI/4.2/UserManagement.svc',
    soapaction => 'http://tempuri.org/IUserManagement/UpdateContactInfo',
    namespace => 'http://tempuri.org/',
    parameters => [
    ], # end parameters
  }, # end UpdateContactInfo
AddMembersToInternalGroup => {
    endpoint => '/Panopto/PublicAPI/4.2/UserManagement.svc',
    soapaction => 'http://tempuri.org/IUserManagement/AddMembersToInternalGroup',
    namespace => 'http://tempuri.org/',
    parameters => [
    ], # end parameters
  }, # end AddMembersToInternalGroup
GetGroup => {
    endpoint => '/Panopto/PublicAPI/4.2/UserManagement.svc',
    soapaction => 'http://tempuri.org/IUserManagement/GetGroup',
    namespace => 'http://tempuri.org/',
    parameters => [
    ], # end parameters
  }, # end GetGroup
CreateUsers => {
    endpoint => '/Panopto/PublicAPI/4.2/UserManagement.svc',
    soapaction => 'http://tempuri.org/IUserManagement/CreateUsers',
    namespace => 'http://tempuri.org/',
    parameters => [
    ], # end parameters
  }, # end CreateUsers
CreateInternalGroup => {
    endpoint => '/Panopto/PublicAPI/4.2/UserManagement.svc',
    soapaction => 'http://tempuri.org/IUserManagement/CreateInternalGroup',
    namespace => 'http://tempuri.org/',
    parameters => [
    ], # end parameters
  }, # end CreateInternalGroup
RemoveMembersFromInternalGroup => {
    endpoint => '/Panopto/PublicAPI/4.2/UserManagement.svc',
    soapaction => 'http://tempuri.org/IUserManagement/RemoveMembersFromInternalGroup',
    namespace => 'http://tempuri.org/',
    parameters => [
    ], # end parameters
  }, # end RemoveMembersFromInternalGroup
GetGroupsByName => {
    endpoint => '/Panopto/PublicAPI/4.2/UserManagement.svc',
    soapaction => 'http://tempuri.org/IUserManagement/GetGroupsByName',
    namespace => 'http://tempuri.org/',
    parameters => [
    ], # end parameters
  }, # end GetGroupsByName
ListGroups => {
    endpoint => '/Panopto/PublicAPI/4.2/UserManagement.svc',
    soapaction => 'http://tempuri.org/IUserManagement/ListGroups',
    namespace => 'http://tempuri.org/',
    parameters => [
    ], # end parameters
  }, # end ListGroups
GetUserByKey => {
    endpoint => '/Panopto/PublicAPI/4.2/UserManagement.svc',
    soapaction => 'http://tempuri.org/IUserManagement/GetUserByKey',
    namespace => 'http://tempuri.org/',
    parameters => [
    ], # end parameters
  }, # end GetUserByKey
ListUsers => {
    endpoint => '/Panopto/PublicAPI/4.2/UserManagement.svc',
    soapaction => 'http://tempuri.org/IUserManagement/ListUsers',
    namespace => 'http://tempuri.org/',
    parameters => [
    ], # end parameters
  }, # end ListUsers
); # end my %methods

use SOAP::Lite;
use Exporter;
use Carp ();

use vars qw(@ISA $AUTOLOAD @EXPORT_OK %EXPORT_TAGS);
@ISA = qw(Exporter SOAP::Lite);
@EXPORT_OK = (keys %methods);
%EXPORT_TAGS = ('all' => [@EXPORT_OK]);

sub _call {
    my ($self, $method) = (shift, shift);
    my $name = UNIVERSAL::isa($method => 'SOAP::Data') ? $method->name : $method;
    my %method = %{$methods{$name}};

    $self->proxy('http://' . Panopto->ServerName . $method{endpoint} || Carp::croak "No server address (proxy) specified")
        unless $self->proxy;
    my @templates = @{$method{parameters}};
    my @parameters = ();
    foreach my $param (@_) {
        if (@templates) {
            my $template = shift @templates;
            my ($prefix,$typename) = SOAP::Utils::splitqname($template->type);
            my $method = 'as_'.$typename;
            # TODO - if can('as_'.$typename) {...}
            my $result = $self->serializer->$method($param, $template->name, $template->type, $template->attr);
            push(@parameters, $template->value($result->[2]));
        }
        else {
            push(@parameters, $param);
        }
    }
    $self->endpoint('http://' . Panopto->ServerName . $method{endpoint})
       ->ns($method{namespace})
       ->on_action(sub{qq!"$method{soapaction}"!});
    $self->serializer->register_ns("http://tempuri.org/","tns");
    my $som = $self->SUPER::call($method => @parameters);
    if ($self->want_som) {
        return $som;
    }
    UNIVERSAL::isa($som => 'SOAP::SOM') ? wantarray ? $som->paramsall : $som->result : $som;
}

sub BEGIN {
    no strict 'refs';
    for my $method (qw(want_som)) {
        my $field = '_' . $method;
        *$method = sub {
            my $self = shift->new;
            @_ ? ($self->{$field} = shift, return $self) : return $self->{$field};
        }
    }
}
no strict 'refs';
for my $method (@EXPORT_OK) {
    my %method = %{$methods{$method}};
    *$method = sub {
        my $self = UNIVERSAL::isa($_[0] => __PACKAGE__)
            ? ref $_[0]
                ? shift # OBJECT
                # CLASS, either get self or create new and assign to self
                : (shift->self || __PACKAGE__->self(__PACKAGE__->new))
            # function call, either get self or create new and assign to self
            : (__PACKAGE__->self || __PACKAGE__->self(__PACKAGE__->new));
        $self->_call($method, @_);
    }
}

sub AUTOLOAD {
    my $method = substr($AUTOLOAD, rindex($AUTOLOAD, '::') + 2);
    return if $method eq 'DESTROY' || $method eq 'want_som';
    die "Unrecognized method '$method'. List of available method(s): @EXPORT_OK\n";
}

1;
